# Generated by Django 4.2.2 on 2023-06-28 01:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TodoList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "createdDate",
                    models.DateTimeField(
                        verbose_name=datetime.datetime(2023, 6, 28, 1, 38, 19, 798512)
                    ),
                ),
            ],
        ),
    ]
