# Generated by Django 4.2.2 on 2023-06-28 02:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todolist",
            name="createdDate",
        ),
        migrations.AddField(
            model_name="todolist",
            name="created_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 28, 2, 48, 42, 35070)
            ),
        ),
        migrations.AddField(
            model_name="todolist",
            name="modified_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 28, 2, 48, 42, 35093)
            ),
        ),
    ]
