# Generated by Django 4.2.2 on 2023-06-28 02:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_remove_todolist_createddate_todolist_created_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todolist",
            name="created_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 28, 2, 50, 1, 754306)
            ),
        ),
        migrations.AlterField(
            model_name="todolist",
            name="modified_date",
            field=models.DateTimeField(null=True),
        ),
    ]
