# Generated by Django 4.2.2 on 2023-06-28 04:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0004_alter_todolist_created_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todolist",
            name="created_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 28, 4, 58, 12, 896615)
            ),
        ),
        migrations.AlterField(
            model_name="todolist",
            name="description",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
